spring:
  application:
    name: billing-service
  jackson:
    # use-jackson2-defaults: true
    serialization:
      fail-on-empty-beans: false
      #write-dates-as-timestamps: false
      indent-output: false
    deserialization:
      fail-on-unknown-properties: false      # Ignore unknown JSON fields
      accept-empty-string-as-null-object: true  # Treat "" as null
  # Database Configuration
  datasource:
    # H2 Database Configuration
    url: jdbc:h2:mem:local-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  datasource:
#    url: jdbc:postgresql://localhost:5432/billing
#    username: postgres
#    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

# Logging Configuration
logging:
  level:
    com.github.lucasdengcn.billing: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# SpringDoc OpenAPI Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    deep-linking: true
    display-request-duration: true
    doc-expansion: full
  api-docs:
    path: /v3/api-docs
  # Additional configurations
  writer-with-order-by-keys: true
  show-actuator: true
